name: CI Pipeline

on:
  push:
    branches:  [ main ]
  pull_request:
    branches:  [ main ]

jobs: 
  lint: 
    runs-on: ubuntu-latest
    steps:

    - name: checkout repository code
      uses: actions/checkout@v4.2.2
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Setup Node.js
      uses: actions/setup-node@v3.9.1

    - name: Install dependencies
      run: npm ci

    - name: run tests (includes linting)
      run: npm test
      
  